# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a21cac398a763a8ed7bfb16d8804f986564b182c1895f35e33178fcc7097abe440a374529b9ef865eeae48cb65bd80b26e7b270c4e5f10d9335f71993eb3916b

test:
  secret_key_base: 33bf0318f74479785865fdb2d91fe289c40e478c810400c2c8c8671cc47a8d9fafd8de1b77f490ca22aab171d51fe6843b2eda0ab897119a57ee47b86a952c96

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
